// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// evolveWFsingle
SEXP evolveWFsingle(const unsigned& N0, const double& mu_n, const double& mu_s, const double& s, const double& h, const double& littler, const Rcpp::IntegerVector& Ns, const unsigned long& seed, const bool& dist = true);
RcppExport SEXP foRward_evolveWFsingle(SEXP N0SEXP, SEXP mu_nSEXP, SEXP mu_sSEXP, SEXP sSEXP, SEXP hSEXP, SEXP littlerSEXP, SEXP NsSEXP, SEXP seedSEXP, SEXP distSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const unsigned& >::type N0(N0SEXP );
        Rcpp::traits::input_parameter< const double& >::type mu_n(mu_nSEXP );
        Rcpp::traits::input_parameter< const double& >::type mu_s(mu_sSEXP );
        Rcpp::traits::input_parameter< const double& >::type s(sSEXP );
        Rcpp::traits::input_parameter< const double& >::type h(hSEXP );
        Rcpp::traits::input_parameter< const double& >::type littler(littlerSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Ns(NsSEXP );
        Rcpp::traits::input_parameter< const unsigned long& >::type seed(seedSEXP );
        Rcpp::traits::input_parameter< const bool& >::type dist(distSEXP );
        SEXP __result = evolveWFsingle(N0, mu_n, mu_s, s, h, littler, Ns, seed, dist);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// WFsingleNmuts
unsigned WFsingleNmuts(SEXP pop);
RcppExport SEXP foRward_WFsingleNmuts(SEXP popSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pop(popSEXP );
        unsigned __result = WFsingleNmuts(pop);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// sampleSingle
Rcpp::List sampleSingle(SEXP pop, const unsigned& nsam, const unsigned long& seed);
RcppExport SEXP foRward_sampleSingle(SEXP popSEXP, SEXP nsamSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pop(popSEXP );
        Rcpp::traits::input_parameter< const unsigned& >::type nsam(nsamSEXP );
        Rcpp::traits::input_parameter< const unsigned long& >::type seed(seedSEXP );
        Rcpp::List __result = sampleSingle(pop, nsam, seed);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
