# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Make an external pointer to a GSL rng *
makeGSLrng <- function(seed) {
    .Call('foRward_makeGSLrng', PACKAGE = 'foRward', seed)
}

#' Sample nsam chromosomes from population
#' @param pop A population returned from evolve_std
#' @param rng A GSLrng
#' @param nsam The sample size
#' @param remove_fixed If TRUE, do not include mutations fixed in the sample in the output.  Default is to include fixations
#' @note If nsam > the population size, an empty list is returned
sampleStd <- function(pop, rng, nsam, remove_fixed = FALSE) {
    .Call('foRward_sampleStd', PACKAGE = 'foRward', pop, rng, nsam, remove_fixed)
}

#' Evolve a single population under multiplicative fitness and arbitrary changes in N
#' @param rng A wrapper to a GSL random number generator
#' @param N0 The initial population size
#' @param mu_n The neutral mutation rate (per gamete per generation)
#' @param mu_n The mutation rate to selected mutations (per gamete per generation)
#' @param s The selection coefficient (for fixed-s models), or the mean of an exponential (for models with a distribution)
#' @param h The dominance of a selected mutation
#' @param littler The recombination rate (per diploid, per generation). 
#' @param Ns A list of populaton sizes.  The length of the list is the number of generations to simulate
#' @param dist If true, simulate a distribution of fitness effects, otherwise treat s as fixed
evolveStd <- function(rng, N0, mu_n, mu_s, s, h, littler, Ns, dist = TRUE) {
    .Call('foRward_evolveStd', PACKAGE = 'foRward', rng, N0, mu_n, mu_s, s, h, littler, Ns, dist)
}

