# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evolve a single population under multiplicative fitness and arbitrary changes in N
evolveWFsingle <- function(pop, mu_n, mu_s, s, h, littler, Ns, seed, dist = TRUE) {
    invisible(.Call('foRward_evolveWFsingle', PACKAGE = 'foRward', pop, mu_n, mu_s, s, h, littler, Ns, seed, dist))
}

